name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        run: |
          docker-compose up -d
          docker ps
          docker exec otus_dz ls -l
      #        docker exec otus_dz composer install
      #        docker exec otus_dz ./vendor/bin/phpunit .

      - name: Composer install
        run: docker exec otus_dz composer install

      - name: Run tests
        run: docker exec otus_dz php ./src/index.php
